# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 937dc3b4b1a01b7a6f4cc5492ceb36f5f25a69437b8bb050d52f136f87e2994123a9fd9e58d61dbbd287a14e69c34c2a24c3838e98fd8b7e7f8f5663e8ecf6cc

test:
  secret_key_base: db8a2fe800c17f46596a72b6fd44347e34351330cb9ba80f8c70b50e97244f61fcf150af28f6169ae3620db46566fb14f706eb5575c2a90a90dc7a0928888427

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
